#!/bin/bash
# build.sh - Build script for Netlify
# This script injects environment variables into env.js at build time

set -e  # Exit on error

echo "🔧 Starting build process..."

# Check if environment variables are set
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "❌ Error: SUPABASE_URL and SUPABASE_ANON_KEY must be set in Netlify environment variables"
    exit 1
fi

echo "📝 Generating env.js with environment variables..."

# Create env.js directly with the environment variables
cat > env.js << EOF
/*
 * env.js - Generated by build script
 * DO NOT EDIT MANUALLY - This file is auto-generated during deployment
 */

(function() {
    "use strict";

    // Variables d'environnement injectées pendant le build
    window.ENV = {
        SUPABASE_URL: '$SUPABASE_URL',
        SUPABASE_ANON_KEY: '$SUPABASE_ANON_KEY'
    };

    // Helpful debug output (doesn't print the key value)
    console.log('🔧 Variables d\'environnement chargées:', {
        url: window.ENV.SUPABASE_URL,
        hasKey: !!window.ENV.SUPABASE_ANON_KEY
    });
})();
EOF

echo "✅ env.js generated successfully"
echo "✅ Build completed"
