# build.ps1 - Script de build pour Windows# build.ps1 - Windows equivalent of build.sh

# Usage: From project root in PowerShell (or CI):

Write-Host "🔧 Génération de env.js..." -ForegroundColor Cyan#   $env:SUPABASE_URL='https://...'; $env:SUPABASE_ANON_KEY='...'; ./build.ps1



# Vérifier que les variables sont définiesif (-not $env:SUPABASE_URL -or -not $env:SUPABASE_ANON_KEY) {

if (-not $env:SUPABASE_URL -or -not $env:SUPABASE_ANON_KEY) {    Write-Error "SUPABASE_URL and SUPABASE_ANON_KEY must be set as environment variables"

    Write-Error "❌ Erreur: Variables SUPABASE_URL et SUPABASE_ANON_KEY manquantes"    exit 1

    Write-Host "Chargez d'abord les variables depuis .env:" -ForegroundColor Yellow}

    Write-Host "  Get-Content .env | ForEach-Object { if (`$_ -match '^([^=]+)=(.*)$') { [Environment]::SetEnvironmentVariable(`$matches[1], `$matches[2], 'Process') } }" -ForegroundColor Yellow

    exit 1$envJsPath = Join-Path $PSScriptRoot 'env.js'

}

Write-Host "📝 Generating env.js with environment variables..."

# Générer env.js

$content = @"# Create env.js directly with the environment variables

(function() {$content = @"

    "use strict";/*

    window.ENV = { * env.js - Generated by build script

        SUPABASE_URL: '$($env:SUPABASE_URL)', * DO NOT EDIT MANUALLY - This file is auto-generated during deployment

        SUPABASE_ANON_KEY: '$($env:SUPABASE_ANON_KEY)' */

    };

    console.log('🔧 Configuration Supabase chargée:', {(function() {

        url: window.ENV.SUPABASE_URL,    "use strict";

        hasKey: !!window.ENV.SUPABASE_ANON_KEY

    });    // Variables d'environnement injectées pendant le build

})();    window.ENV = {

"@        SUPABASE_URL: '$($env:SUPABASE_URL)',

        SUPABASE_ANON_KEY: '$($env:SUPABASE_ANON_KEY)'

Set-Content -Path "env.js" -Value $content -Encoding UTF8    };

Write-Host "✅ env.js généré avec succès" -ForegroundColor Green

    // Helpful debug output (doesn't print the key value)
    console.log('🔧 Variables d\'environnement chargées:', {
        url: window.ENV.SUPABASE_URL,
        hasKey: !!window.ENV.SUPABASE_ANON_KEY
    });
})();
"@

# Write to env.js
Set-Content -Path $envJsPath -Value $content -Encoding UTF8
Write-Host "✅ env.js generated from environment variables"