# build.ps1 - Windows equivalent of build.sh
# Usage: From project root in PowerShell (or CI):
#   $env:SUPABASE_URL='https://...'; $env:SUPABASE_ANON_KEY='...'; ./build.ps1

if (-not $env:SUPABASE_URL -or -not $env:SUPABASE_ANON_KEY) {
    Write-Error "SUPABASE_URL and SUPABASE_ANON_KEY must be set as environment variables"
    exit 1
}

$envJsPath = Join-Path $PSScriptRoot 'env.js'

Write-Host "📝 Generating env.js with environment variables..."

# Create env.js directly with the environment variables
$content = @"
/*
 * env.js - Generated by build script
 * DO NOT EDIT MANUALLY - This file is auto-generated during deployment
 */

(function() {
    "use strict";

    // Variables d'environnement injectées pendant le build
    window.ENV = {
        SUPABASE_URL: '$($env:SUPABASE_URL)',
        SUPABASE_ANON_KEY: '$($env:SUPABASE_ANON_KEY)'
    };

    // Helpful debug output (doesn't print the key value)
    console.log('🔧 Variables d\'environnement chargées:', {
        url: window.ENV.SUPABASE_URL,
        hasKey: !!window.ENV.SUPABASE_ANON_KEY
    });
})();
"@

# Write to env.js
Set-Content -Path $envJsPath -Value $content -Encoding UTF8
Write-Host "✅ env.js generated from environment variables"