#!/bin/bash#!/bin/bash

# build.sh - Script de build pour Netlify# build.sh - Build script for Netlify

# This script injects environment variables into env.js at build time

set -e

set -e  # Exit on error

echo "🔧 Génération de env.js..."

echo "🔧 Starting build process..."

# Vérifier que les variables sont définies

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then# Check if environment variables are set

    echo "❌ Erreur: Variables SUPABASE_URL et SUPABASE_ANON_KEY manquantes"if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then

    exit 1    echo "❌ Error: SUPABASE_URL and SUPABASE_ANON_KEY must be set in Netlify environment variables"

fi    exit 1

fi

# Générer env.js depuis le template

cat > env.js << EOFecho "📝 Generating env.js with environment variables..."

(function() {

    "use strict";# Create env.js directly with the environment variables

    window.ENV = {cat > env.js << EOF

        SUPABASE_URL: '$SUPABASE_URL',/*

        SUPABASE_ANON_KEY: '$SUPABASE_ANON_KEY' * env.js - Generated by build script

    }; * DO NOT EDIT MANUALLY - This file is auto-generated during deployment

    console.log('🔧 Configuration Supabase chargée:', { */

        url: window.ENV.SUPABASE_URL,

        hasKey: !!window.ENV.SUPABASE_ANON_KEY(function() {

    });    "use strict";

})();

EOF    // Variables d'environnement injectées pendant le build

    window.ENV = {

echo "✅ env.js généré avec succès"        SUPABASE_URL: '$SUPABASE_URL',

        SUPABASE_ANON_KEY: '$SUPABASE_ANON_KEY'
    };

    // Helpful debug output (doesn't print the key value)
    console.log('🔧 Variables d\'environnement chargées:', {
        url: window.ENV.SUPABASE_URL,
        hasKey: !!window.ENV.SUPABASE_ANON_KEY
    });
})();
EOF

echo "✅ env.js generated successfully"
echo "✅ Build completed"
